image: python:3.10

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
  artifacts:
    paths:
      - myapp/
    expire_in: 1 hour
  cache:
    paths:
      - .cache/pip
      - venv/


test_job:
  stage: test
  script:
    - echo "Running tests..."
    - pytest

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Add deployment commands here
  only:
    - main