stages:
  - build
  - test
  - publish
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_USER/$IMAGE_NAME
  DOCKER_TAG: $IMAGE_TAG
  DOCKER_HOST: "tcp://docker:2375"

build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_HOST: $DOCKER_HOST
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

test:
  stage: test
  image: python:3.10-slim

  dependencies:
    - build
  script:
    - echo "TESTING FASTAPI PROJECT...."
    # - pip install -r requirements.txt

    - pytest
  only: 
    - main


# Publish the new project Image to dockerhub 
publish:
  stage: publish
  image: docker:latest
  dependencies:
    - build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - ls
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  tags:
    - dind
  only:
    - main
  

deploy:
  stage: deploy
  dependencies:
    - build
  image: ubuntu:22.04
  before_script:
    # Installs on Ubuntu dist.
    - apt-get update && apt install openssh-client
  
  script:
    # Store key in file
    - echo "$AWS_SSH_KEY" > "key.pem"

    # Owner read access only
    - chmod 400 key.pem 

    # SSH into AWS EC2 instance
    - ssh -i "key.pem" $AWS_USERNAME@$AWS_PUBLIC_DNS "
      docker container rm -f $SERVER_CONTAINER_NAME || true && 
      docker image rm -f $DOCKER_IMAGE:$DOCKER_TAG || true &&
      docker run --name $SERVER_CONTAINER_NAME -d -p 80:8080 $DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main