stages:
  - test
  - deploy

# Test project
run-tests:
  stage: test
  image: python:3.10-slim
  script:
    - echo "TESTING FASTAPI PROJECT...."

    - pip install -U pip
    - pip install -r requirements.txt
    - pytest
  only: 
    - main

deploy-railway:
  stage: deploy
  image: ubuntu:22.04
  only:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d