image: python:3.10

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt 
    - echo "Building the project..."
    - uvicorn src.main:app --reload

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - pytest
