name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  Dev-Deployment:
    name: Dev Deployment
    runs-on: ubuntu-22.04
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout@v2

    env:
      DEV_CONFIG_ENV: ${{ secrets.DEV_CONFIG_ENV }}
      CONTAINER_IMAGE_NAME: vlecture-api-dev
      AWS_REGION: us-west-2
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      # - name: Configure AWS Credentials 1
      #   id: creds
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-region: ${{ env.AWS_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     role-session-name: samplerolesession
      #     output-credentials: true

      # - name: get caller identity 1
      #   run: |
      #     aws sts get-caller-identity

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ steps.creds.outputs.aws-session-token }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200
          role-session-name: GithubConfigAWSCreds
          role-skip-session-tagging: true

      # - name: get caller identity2
      #   run: |
      #     aws sts get-caller-identity
      
      # Old ver
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to AWS ECR
        env:
          DEV_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DEV_ECR_REPOSITORY: $CONTAINER_IMAGE_NAME
        run: |
          docker build -t $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$IMAGE_TAG .
          docker tag "$DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$IMAGE_TAG" "$DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:latest"

      - name: Push to AWS ECR
        run: |
          docker push $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$IMAGE_TAG
          docker push $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:latest
      
      - name: Pull from ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          image: $CONTAINER_IMAGE_NAME:$IMAGE_TAG
          local-image: CONTAINER_IMAGE_NAME
          direction: pull
      
      - name: Pull latest image and run container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATEKEY }}
          envs: DEV_CONFIG_ENV,AWS_SECRET_ACCESS_KEY,AWS_ACCESS_KEY_ID,DEV_ECR_REGISTRY,DEV_ECR_REPOSITORY
          script: |
            mkdir -pv ./app/vlecture-api
            cd ./app/vlecture-api
            echo $DEV_CONFIG_ENV | tr ' ' '\n' > .env
            aws ecr get-login-password | docker login -u AWS --password-stdin "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$(aws configure get region).amazonaws.com"

            docker rm -f vlecture-api
            docker pull "$REGISTRY/$REGISTRY_IMAGE:latest"
            docker run -d --name vlecture-api \
              --restart always \
              -v "$(pwd)/.env:/app/vlecture-api/.env:ro" \
              -p "8080:8080" \
              "$REGISTRY/$REGISTRY_IMAGE:latest"


# Source: https://dev.to/slsbytheodo/configure-authentication-to-your-aws-account-in-your-github-actions-ci-13p3