name: vlecture deploy to railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest
      env:
        DB_URL: ${{ secrets.DB_URL }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
      
    # - name: Login to Docker Hub
    #   run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    # - name: Build and push Docker image
    #   run: |
    #     docker buildx create --use
    #     docker buildx build \
    #       --file Dockerfile \
    #       --tag ${{ secrets.DOCKERHUB_USERNAME }}/ppl-vlecture-fastapi:latest \
    #       --push .

    # env:
    #   DOCKER_CLI_EXPERIMENTAL: enabled
    #   DOCKER_BUILDKIT: 1
